### ISSUE TITLE
libxm2 download broken in bootstrap

### ISSUE THREAD

**Issue by kostrzewa** [HISKP-LQCD/chroma-auxiliary-scripts#5]

**Comment by kostrzewa** [comment]
it seems gnome has moved to gitlab

**Comment by martin-ueding** [comment]
I had fixed this some time ago but not uploaded the compiled script to my website. This is done now, it should be working again.

**Comment by kostrzewa** [comment]
my bad, I probably forgot to regenerate the script

**Comment by martin-ueding** [comment]
No problem, I mean we are not [these guys](https://lists.suckless.org/dev/1512/27818.html).
